# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 6
paginate_path: "/blog/page/:num/"


source: source
destination: _site
safe: false
encoding: utf-8
sass:
  sass_dir: _scss
  style: compressed # expanded

kramdown:
  input: GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# SEO settings
title: Huailiang Blog
description: "关于前端与设计、黑客与画家 | 怀亮，Web & Mobile Lover，Software Engineer，Game Designer | 这里是 @Huailiang怀亮 的个人博客，与你一起发现更大的世界。"
keywords: "怀亮, Huailiang怀亮, Huailiang, Unity, Tensorflow, AR, 怀亮的博客, Huailiang Blog, 博客, U3D, 互联网, AR, Tensorflow"
url: https://huailiang.github.io
baseurl: ""



# google_analytics: UA-52446115-1
repo: https://github.com/huailiang
disqus_shortname: "huailiang"

# Author settings
author:
  name      : 彭怀亮
  job       : 游戏开发工程师
  thumb     : /img/author.jpg
  email     : nandomoreira.me@gmail.com
  url       : https://huailiang.github.io
  github    : https://github.com/huailiang
  twitter   : https://twitter.com/penghuailiang
  facebook  : https://www.facebook.com/profile.php?id=100004290725320
  linkedin  : https://www.linkedin.com/in/penghuailiang/

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]